# Generated by Django 4.1.6 on 2023-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colaboradores.setor'),
        ),
    ]
