# Generated by Django 4.1.6 on 2023-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_remove_colaborador_categoria_alter_colaborador_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='aniversario',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
