# Generated by Django 4.1.6 on 2023-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_aniversario'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
