# Generated by Django 4.1.6 on 2023-02-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_colaborador_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
