# Generated by Django 4.1.6 on 2023-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_colaborador_avatar_alter_colaborador_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
